apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-eks-gitops
  labels:
    app: python-eks-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-eks-gitops
  template:
    metadata:
      labels:
        app: python-eks-gitops
    spec:
      containers:
        - name: python-eks-gitops
          image: 755729228993.dkr.ecr.ap-south-1.amazonaws.com/python-eks-gitops:cbee26ddbce02b74d0ce3b8b1c1505fafc9ed3b6
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"