apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-eks-gitops
  labels:
    app: python-eks-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-eks-gitops
  template:
    metadata:
      labels:
        app: python-eks-gitops
    spec:
      containers:
        - name: python-eks-gitops
          image: 755729228993.dkr.ecr.ap-south-1.amazonaws.com/python-eks-gitops:d5a34b2db7602170b966a37d76871f485e339f5c
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"