apiVersion: v1
kind: Service

metadata:
  name: python-eks-gitops

spec:
  type: ClusterIP

  selector:
    app: python-eks-gitops

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000