name: Terraform

on:

  # --------------------------------------------------
  # Manual execution
  # --------------------------------------------------
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        type: choice
        options:
          - create
          - destroy
        default: create


permissions:
  id-token: write
  contents: read


env:
  AWS_REGION: ap-south-1


jobs:
  # --------------------------------------------------
  # Terraform
  # --------------------------------------------------
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      # ----------------------------------------------
      # Checkout
      # ----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4


      # ----------------------------------------------
      # AWS OIDC authentication
      # ----------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::755729228993:role/GitHubActions-Terraform
          aws-region: ${{ env.AWS_REGION }}
          audience: https://github.com/aasthakumarii


      # ----------------------------------------------
      # Verify AWS authentication
      # ----------------------------------------------
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity


      # ----------------------------------------------
      # Setup Terraform
      # ----------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # ----------------------------------------------
      # Terraform Init
      # ----------------------------------------------
      - name: Terraform Init
        run: |
          terraform init


      # ----------------------------------------------
      # Terraform Format
      # ----------------------------------------------
      - name: Terraform Format Check
        run: |
          terraform fmt -check


      # ----------------------------------------------
      # Terraform Validate
      # ----------------------------------------------
      - name: Terraform Validate
        run: |
          terraform validate


      # ----------------------------------------------
      # Terraform Plan
      # ----------------------------------------------
      - name: Terraform Plan
        run: |
          terraform plan


      # ----------------------------------------------
      # Terraform Create
      # ----------------------------------------------
      - name: Terraform Create
        if: inputs.action == 'create'
        run: |
          terraform apply -auto-approve


      # ----------------------------------------------
      # Terraform Destroy
      # ----------------------------------------------
      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: |
          terraform destroy -auto-approve